version: "3"
services:
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        # image: naaltunian/frontend
        ports:
            - "3000:3000"
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: ["npm", "run", "test"]